export const EMOJIS: { name: string; char: string; category: string; aliases: string[] }[] = [
    { name: 'grinning', char: '😀', category: "smiles", aliases: ['grinning_face'] },
    { name: 'grinning_big_eyes', char: '😃', category: "smiles", aliases: ['big_eyes_smile', 'excited_face'] },
    { name: 'grinning_smiling_eyes', char: '😄', category: "smiles", aliases: ['smiling_eyes', 'cheerful'] },
    { name: 'beaming_smiling_eyes', char: '😁', category: "smiles", aliases: ['beaming', 'big_smile'] },
    { name: 'grinning_squinting_face', char: '😆', category: "smiles", aliases: ['squinting', 'laughing'] },
    { name: 'grinning_sweat', char: '😅', category: "smiles", aliases: ['sweat_smile', 'nervous_smile'] },
    { name: 'rofl', char: '🤣', category: "smiles", aliases: ['rolling_on_floor_laughing', 'hilarious'] },
    { name: 'joy', char: '😂', category: "smiles", aliases: ['tears_of_joy', 'lol'] },
    { name: 'slight_smile', char: '🙂', category: "smiles", aliases: ['simple_smile', 'soft_smile'] },
    { name: 'wink', char: '😉', category: "smiles", aliases: ['winking', 'flirty'] },
    { name: 'smile_with_eyes', char: '😊', category: "smiles", aliases: ['blush', 'warm_smile'] },
    { name: 'smile_halo', char: '😇', category: "smiles", aliases: ['angel', 'halo_face'] },
    { name: 'smile_hearts', char: '🥰', category: "smiles", aliases: ['in_love', 'hearts_face'] },
    { name: 'smile_heart_eyes', char: '😍', category: "smiles", aliases: ['heart_eyes', 'love_face'] },
    { name: 'star_struck', char: '🤩', category: "smiles", aliases: ['star_eyes', 'amazed'] },
    { name: 'kiss_blow', char: '😘', category: "smiles", aliases: ['blowing_kiss', 'kiss_face'] },
    { name: 'kiss', char: '😗', category: "smiles", aliases: ['simple_kiss', 'kissy'] },
    { name: 'smile', char: '☺️', category: "smiles", aliases: ['content', 'gentle_smile'] },
    { name: 'kiss_closed_eyes', char: '😚', category: "smiles", aliases: ['closed_eyes_kiss', 'sweet_kiss'] },
    { name: 'kiss_with_eyes', char: '😙', category: "smiles", aliases: ['smiling_kiss', 'happy_kiss'] },
    { name: 'smile_tear', char: '🥲', category: "smiles", aliases: ['tearful_smile', 'bittersweet'] },
    { name: 'smirk', char: '😏', category: "smiles", aliases: ['smirking', 'sly_smile'] },
    { name: 'savouring_food', char: '😋', category: "smiles", aliases: ['yum', 'delicious'] },
    { name: 'tongue_face', char: '😛', category: "smiles", aliases: ['playful', 'tongue_out'] },
    { name: 'wink_tongue', char: '😜', category: "smiles", aliases: ['crazy_face', 'winking_tongue'] },
    { name: 'zany', char: '🤪', category: "smiles", aliases: ['wild_face', 'goofy'] },
    { name: 'tongue_squint', char: '😝', category: "smiles", aliases: ['squint_tongue', 'silly_face'] },
    { name: 'money_face', char: '🤑', category: "smiles", aliases: ['rich', 'cash_face'] },
    { name: 'smile_open_hands', char: '🤗', category: "smiles", aliases: ['hug', 'open_arms'] },
    { name: 'hand_over_face_joy', char: '🤭', category: "smiles", aliases: ['embarrassed_laugh', 'shy_laugh'] },
    { name: 'hand_over_face_embarassed', char: '🫢', category: "smiles", aliases: ['shy_face', 'embarrassed'] },
    { name: 'peeking_eye', char: '🫣', category: "smiles", aliases: ['peek', 'curious'] },
    { name: 'shush', char: '🤫', category: "smiles", aliases: ['quiet', 'shh'] },
    { name: 'thinking', char: '🤔', category: "smiles", aliases: ['ponder', 'hmm'] },
    { name: 'salute', char: '🫡', category: "smiles", aliases: ['respect', 'saluting'] },
    { name: 'drool', char: '🤤', category: "smiles", aliases: ['drooling', 'hungry'] },
    { name: 'cowboy', char: '🤠', category: "smiles", aliases: ['cowboy_hat', 'yee_haw'] },
    { name: 'partying_face', char: '🥳', category: "smiles", aliases: ['party', 'celebrate'] },
    { name: 'disguised_face', char: '🥸', category: "smiles", aliases: ['disguise', 'incognito'] },
    { name: 'sunglasses_face', char: '😎', category: "smiles", aliases: ['cool', 'shades'] },
    { name: 'nerd', char: '🤓', category: "smiles", aliases: ['nerdy', 'geek'] },
    { name: 'monocle_face', char: '🧐', category: "smiles", aliases: ['monocle', 'inspecting'] },
    { name: 'upside_down_face', char: '🙃', category: "smiles", aliases: ['upside_down', 'silly'] },
    { name: 'melting_face', char: '🫠', category: "smiles", aliases: ['melting', 'heat_face'] },
    { name: 'zipped_mouth', char: '🤐', category: "smiles", aliases: ['zipper_mouth', 'secret'] },
    { name: 'raised_eyebrow', char: '🤨', category: "smiles", aliases: ['suspicious', 'questioning'] },
    { name: 'neutral', char: '😐', category: "smiles", aliases: ['neutral_face', 'meh'] },
    { name: 'expressionless_face', char: '😑', category: "smiles", aliases: ['blank_face', 'expressionless'] },
    { name: 'no_mouth', char: '😶', category: "smiles", aliases: ['mouthless', 'silent'] },
    { name: 'dotted_face', char: '🫥', category: "smiles", aliases: ['dotted', 'faded_face'] },
    { name: 'face_in_clouds', char: '😶‍🌫️', category: "smiles", aliases: ['cloud_face', 'foggy'] },
    { name: 'unamused_face', char: '😒', category: "smiles", aliases: ['unamused', 'displeased'] },
    { name: 'rolling_eyes', char: '🙄', category: "smiles", aliases: ['eye_roll', 'annoyed'] },
    { name: 'grimacing_face', char: '😬', category: "smiles", aliases: ['grimace', 'awkward'] },
    { name: 'exhaling_face', char: '😮‍💨', category: "smiles", aliases: ['exhale', 'relief'] },
    { name: 'lying_face', char: '🤥', category: "smiles", aliases: ['liar', 'lying'] },
    // { name: 'head_shaking_horizontally', char: '🙂‍↔️', category: "smiles", aliases: ['shake_horizontal', 'no_face'] }, // ZWJ Emoji
    // { name: 'head_shaking_vertically', char: '🙂‍↕️', category: "smiles", aliases: ['shake_vertical', 'yes_face'] }, // ZWZ Emoji
    { name: 'relieved_face', char: '😌', category: "smiles", aliases: ['relieved', 'calm_face'] },
    { name: 'pensive_face', char: '😔', category: "smiles", aliases: ['pensive', 'thoughtful'] },
    { name: 'sleepy_face', char: '😪', category: "smiles", aliases: ['sleepy', 'tired'] },
    { name: 'sleeping_face', char: '😴', category: "smiles", aliases: ['sleeping', 'zzz'] },
    { name: 'medical_mask_face', char: '😷', category: "smiles", aliases: ['mask', 'sick_face'] },
    { name: 'thermometer_face', char: '🤒', category: "smiles", aliases: ['thermometer', 'fever'] },
    { name: 'bandaged_head', char: '🤕', category: "smiles", aliases: ['injured', 'bandage'] },
    { name: 'nauseated_face', char: '🤢', category: "smiles", aliases: ['nausea', 'sick'] },
    { name: 'vomiting_face', char: '🤮', category: "smiles", aliases: ['vomit', 'throwing_up'] },
    { name: 'sneeze', char: '🤧', category: "smiles", aliases: ['sneezing', 'allergy'] },
    { name: 'hot', char: '🥵', category: "smiles", aliases: ['hot_face', 'overheated'] },
    { name: 'cold', char: '🥶', category: "smiles", aliases: ['cold_face', 'freezing'] },
    { name: 'woozy_face', char: '🥴', category: "smiles", aliases: ['woozy', 'dizzy'] },
    { name: 'crossed_face', char: '😵', category: "smiles", aliases: ['crossed_eyes', 'dead_face'] },
    { name: 'dizzy_face', char: '😵‍💫', category: "smiles", aliases: ['dizzy', 'spinning'] },
    { name: 'mindblown', char: '🤯', category: "smiles", aliases: ['exploding_head', 'mind_blown'] },
    { name: 'yawning_face', char: '🥱', category: "smiles", aliases: ['yawn', 'tired_face'] },
    { name: 'confused_face', char: '😕', category: "smiles", aliases: ['confused', 'unsure'] },
    { name: 'diagonal_mouth', char: '🫤', category: "smiles", aliases: ['diagonal', 'meh_face'] },
    { name: 'worried_face', char: '😟', category: "smiles", aliases: ['worried', 'concerned'] },
    { name: 'slight_frown', char: '🙁', category: "smiles", aliases: ['slight_frown', 'mild_sad'] },
    { name: 'frown', char: '☹️', category: "smiles", aliases: ['frowning', 'sad_face'] },
    { name: 'open_mouth_face', char: '😮', category: "smiles", aliases: ['open_mouth', 'surprised'] },
    { name: 'hushed_face', char: '😯', category: "smiles", aliases: ['hushed', 'astonished'] },
    { name: 'astonished_face', char: '😲', category: "smiles", aliases: ['astonished', 'shocked'] },
    { name: 'flushed_face', char: '😳', category: "smiles", aliases: ['flushed', 'embarrassed_face'] },
    { name: 'pleading_face', char: '🥺', category: "smiles", aliases: ['pleading', 'begging'] },
    { name: 'face_holding_back_tears', char: '🥹', category: "smiles", aliases: ['holding_tears', 'emotional'] },
    { name: 'frown_open_mouth_face', char: '😦', category: "smiles", aliases: ['frown_open', 'worried_open'] },
    { name: 'anguished_face', char: '😧', category: "smiles", aliases: ['anguished', 'distressed'] },
    { name: 'fear', char: '😨', category: "smiles", aliases: ['fearful', 'scared'] },
    { name: 'anxiety', char: '😰', category: "smiles", aliases: ['anxious', 'nervous'] },
    { name: 'sad_relieved_face', char: '😥', category: "smiles", aliases: ['sad_relieved', 'tearful'] },
    { name: 'cry', char: '😢', category: "smiles", aliases: ['crying', 'tears'] },
    { name: 'sob', char: '😭', category: "smiles", aliases: ['sobbing', 'crying_hard'] },
    { name: 'screaming_face', char: '😱', category: "smiles", aliases: ['scream', 'horror'] },
    { name: 'confounded_face', char: '😖', category: "smiles", aliases: ['confounded', 'frustrated'] },
    { name: 'persevering_face', char: '😣', category: "smiles", aliases: ['persevering', 'struggling'] },
    { name: 'disappointed_face', char: '😞', category: "smiles", aliases: ['disappointed', 'let_down'] },
    { name: 'downcast_sweat_face', char: '😓', category: "smiles", aliases: ['downcast_sweat', 'worried_sweat'] },
    { name: 'weary_face', char: '😩', category: "smiles", aliases: ['weary', 'exhausted'] },
    { name: 'tired_face', char: '😫', category: "smiles", aliases: ['tired', 'fatigued'] },
    { name: 'steaming_face', char: '😤', category: "smiles", aliases: ['steam_nose', 'angry_steam'] },
    { name: 'enraged_face', char: '😡', category: "smiles", aliases: ['enraged', 'furious'] },
    { name: 'angry_face', char: '😠', category: "smiles", aliases: ['angry', 'mad_face'] },
    { name: 'swearing_face', char: '🤬', category: "smiles", aliases: ['cursing', 'swear'] },
    { name: 'smiling_devil_face', char: '😈', category: "smiles", aliases: ['devil_smile', 'evil_smile'] },
    { name: 'angry_devil_face', char: '👿', category: "smiles", aliases: ['devil_angry', 'evil_angry'] },
    { name: 'skull', char: '💀', category: "smiles", aliases: ['skull_face', 'dead'] },
    { name: 'skull_crossbones', char: '☠️', category: "smiles", aliases: ['crossbones', 'danger'] },
    { name: 'poop', char: '💩', category: "smiles", aliases: ['poo', 'dung', 'shit', 'turd'] },
    { name: 'clown', char: '🤡', category: "smiles", aliases: ['clown_face', 'joker'] },
    { name: 'ogre', char: '👹', category: "smiles", aliases: ['ogre_face', 'monster'] },
    { name: 'goblin', char: '👺', category: "smiles", aliases: ['goblin_face', 'troll'] },
    { name: 'ghost', char: '👻', category: "smiles", aliases: ['ghost_face', 'spooky'] },
    { name: 'alien', char: '👽', category: "smiles", aliases: ['alien_face', 'extraterrestrial'] },
    { name: 'pixel_alien', char: '👾', category: "smiles", aliases: ['space_invader', 'pixel_monster'] },
    { name: 'robot', char: '🤖', category: "smiles", aliases: ['robot_face', 'android'] },
    { name: 'grinning_cat', char: '😺', category: "smiles", aliases: ['cat_smile', 'happy_cat'] },
    { name: 'grinning_cat_smiling_eyes', char: '😸', category: "smiles", aliases: ['cat_smiling_eyes', 'cheerful_cat'] },
    { name: 'joyful_cat', char: '😹', category: "smiles", aliases: ['cat_tears_joy', 'laughing_cat'] },
    { name: 'heart_eyed_cat', char: '😻', category: "smiles", aliases: ['cat_heart_eyes', 'love_cat'] },
    { name: 'evil_cat', char: '😼', category: "smiles", aliases: ['smirking_cat', 'sly_cat'] },
    { name: 'kissing_cat', char: '😽', category: "smiles", aliases: ['cat_kiss', 'kissy_cat'] },
    { name: 'weary_cat', char: '🙀', category: "smiles", aliases: ['cat_weary', 'scared_cat'] },
    { name: 'crying_cat', char: '😿', category: "smiles", aliases: ['cat_cry', 'sad_cat'] },
    { name: 'pouting_cat', char: '😾', category: "smiles", aliases: ['cat_pout', 'angry_cat'] },
    { name: 'see_no_evil_monkey', char: '🙈', category: "smiles", aliases: ['see_no_evil', 'monkey_see'] },
    { name: 'hear_no_evil_monkey', char: '🙉', category: "smiles", aliases: ['hear_no_evil', 'monkey_hear'] },
    { name: 'speak_no_evil_monkey', char: '🙊', category: "smiles", aliases: ['speak_no_evil', 'monkey_speak'] },
    { name: 'wave', char: '👋', category: "people", aliases: ['waving_hand'] },
    { name: 'raised_back_of_hand', char: '🤚', category: "people", aliases: ['back_of_hand'] },
    { name: 'raised_hand_with_fingers_splayed', char: '🖐️', category: "people", aliases: ['hand_with_fingers_splayed', 'hand_splayed'] },
    { name: 'raised_hand', char: '✋', category: "people", aliases: ['hand'] },
    { name: 'vulcan_salute', char: '🖖', category: "people", aliases: ['spock-hand', 'vulcan', 'raised_hand_with_part_between_middle_and_ring_fingers'] },
    { name: 'rightwards_hand', char: '🫱', category: "people", aliases: [] },
    { name: 'leftwards_hand', char: '🫲', category: "people", aliases: [] },
    { name: 'palm_down_hand', char: '🫳', category: "people", aliases: [] },
    { name: 'palm_up_hand', char: '🫴', category: "people", aliases: [] },
    { name: 'leftwards_pushing_hand', char: '🫷', category: "people", aliases: [] },
    { name: 'rightwards_pushing_hand', char: '🫸', category: "people", aliases: [] },
    { name: 'ok_hand', char: '👌', category: "people", aliases: [] },
    { name: 'pinched_fingers', char: '🤌', category: "people", aliases: [] },
    { name: 'pinching_hand', char: '🤏', category: "people", aliases: [] },
    { name: 'v', char: '✌️', category: "people", aliases: ['victory_hand'] },
    { name: 'crossed_fingers', char: '🤞', category: "people", aliases: ['hand_with_index_and_middle_fingers_crossed', 'fingers_crossed', 'hand_with_index_and_middle_finger_crossed'] },
    { name: 'hand_with_index_finger_and_thumb_crossed', char: '🫰', category: "people", aliases: [] },
    { name: 'love_you_gesture', char: '🤟', category: "people", aliases: ['i_love_you_hand_sign'] },
    { name: 'sign_of_the_horns', char: '🤘', category: "people", aliases: ['metal', 'the_horns'] },
    { name: 'call_me_hand', char: '🤙', category: "people", aliases: ['call_me'] },
    { name: 'point_left', char: '👈', category: "people", aliases: ['backhand_index_pointing_left'] },
    { name: 'point_right', char: '👉', category: "people", aliases: ['backhand_index_pointing_right'] },
    { name: 'point_up_2', char: '👆', category: "people", aliases: ['backhand_index_pointing_up'] },
    { name: 'middle_finger', char: '🖕', category: "people", aliases: ['reversed_hand_with_middle_finger_extended', 'fu'] },
    { name: 'point_down', char: '👇', category: "people", aliases: ['backhand_index_pointing_down'] },
    { name: 'point_up', char: '☝️', category: "people", aliases: ['index_pointing_up'] },
    { name: 'index_pointing_at_the_viewer', char: '🫵', category: "people", aliases: [] },
    { name: 'thumbsup', char: '👍', category: "people", aliases: ['thumbs_up', '+1', 'thumbup'] },
    { name: 'thumbsdown', char: '👎', category: "people", aliases: ['thumbs_down', '-1', 'thumbdown'] },
    { name: 'fist', char: '✊', category: "people", aliases: ['raised_fist', 'fist_raised'] },
    { name: 'punch', char: '👊', category: "people", aliases: ['oncoming_fist', 'facepunch', 'fist_oncoming'] },
    { name: 'left_facing_fist', char: '🤛', category: "people", aliases: ['fist_left', 'left-facing_fist', 'left_fist'] },
    { name: 'right_facing_fist', char: '🤜', category: "people", aliases: ['fist_right', 'right-facing_fist', 'right_fist'] },
    { name: 'clap', char: '👏', category: "people", aliases: ['clapping_hands'] },
    { name: 'raised_hands', char: '🙌', category: "people", aliases: ['raising_hands'] },
    { name: 'heart_hands', char: '🫶', category: "people", aliases: [] },
    { name: 'open_hands', char: '👐', category: "people", aliases: [] },
    { name: 'palms_up_together', char: '🤲', category: "people", aliases: [] },
    { name: 'handshake', char: '🤝', category: "people", aliases: ['shaking_hands'] },
    { name: 'pray', char: '🙏', category: "people", aliases: ['folded_hands'] },
    { name: 'writing_hand', char: '✍️', category: "people", aliases: [] },
    { name: 'nail_care', char: '💅', category: "people", aliases: ['nail_polish'] },
    { name: 'selfie', char: '🤳', category: "people", aliases: [] },
    { name: 'muscle', char: '💪', category: "people", aliases: ['flexed_biceps'] },
    { name: 'mechanical_arm', char: '🦾', category: "people", aliases: [] },
    { name: 'mechanical_leg', char: '🦿', category: "people", aliases: [] },
    { name: 'leg', char: '🦵', category: "people", aliases: [] },
    { name: 'foot', char: '🦶', category: "people", aliases: [] },
    { name: 'ear', char: '👂', category: "people", aliases: [] },
    { name: 'ear_with_hearing_aid', char: '🦻', category: "people", aliases: [] },
    { name: 'nose', char: '👃', category: "people", aliases: [] },
    { name: 'brain', char: '🧠', category: "people", aliases: [] },
    { name: 'anatomical_heart', char: '🫀', category: "people", aliases: [] },
    { name: 'lungs', char: '🫁', category: "people", aliases: [] },
    { name: 'tooth', char: '🦷', category: "people", aliases: [] },
    { name: 'bone', char: '🦴', category: "people", aliases: [] },
    { name: 'eyes', char: '👀', category: "people", aliases: [] },
    { name: 'eye', char: '👁️', category: "people", aliases: [] },
    { name: 'tongue', char: '👅', category: "people", aliases: [] },
    { name: 'lips', char: '👄', category: "people", aliases: ['mouth'] },
    { name: 'biting_lip', char: '🫦', category: "people", aliases: [] },
    { name: 'footprints', char: '👣', category: "people", aliases: [] },
    { name: 'fingerprint', char: '🫆', category: "people", aliases: [] },
    { name: 'dna', char: '🧬', category: "people", aliases: [] },
    { name: 'drop_of_blood', char: '🩸', category: "people", aliases: [] },
];
